version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ayomide20?
      POSTGRES_DB: prisma-with-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/libpostgresql/data

  app:
    build: .
    container_name: express-api
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:Ayomide20%3F@postgres_db:5432/prisma-with-postgres?schema=public
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: [ "sh", "-c", "npx prisma generate && node src/server.js" ]

volumes:
  postgres_data:
